### ISSUE TITLE
[FIXED] Core feature, custom led program uploading does not work

### ISSUE THREAD

**Issue by Odaller** [CelliesProjects/aquacontrol32#39]
Hello,

Probably I'm doing something wrong but I got a problem with the key feature of the aquacontrol32.
Oled works, Lights_ON works, but if i'm going in Lights_auto mode and i try to upload new timers to the controller, it doesn't do anything. If I go to another webpage and back to the editor, the timers I set before have vanished.

What could be going wrong?

Thanks for your reply.

**Comment by CelliesProjects** [comment]
Most common mistake if everything is working except uploading is a wrong partition scheme.
( Happens to me every time I switch sketch or board)
Did you use a partition with ffat?
If the aquacontrol file manager shows `0 Bytes free / 0 Bytes total` you probably compiled with a spiffs instead of a ffat partition.
Check `Tools>Partition Scheme` in the Arduino IDE to make sure you selected the right option.

**Comment by Odaller** [comment]
Yes, that did the trick. I overlooked that in your compile notes... Thanks a lot.
